name: Build

on: [push]

jobs:
  build:
    env:
      SEC_IP: ${{ secrets.IP }}
      SEC_KEY: ${{ secrets.KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "$SEC_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -p 56789 $SEC_IP >> ~/.ssh/known_hosts
      - name: Install dependencies
        run: |
          npm ci
          cd themes/suka
          npm ci --production
          cd -
      - name: Hexo Generate
        run: |
          npx hexo g -d
      - name: Rsync to server
        run: |
          rsync -rvz -e 'ssh -p 56789' public/* root@$SEC_IP:/home/wwwroot/blog/
