name: Hexo

on:
  push:
    branches: [master]

env:
  IP: ${{ secrets.IP }}
  KEY: ${{ secrets.KEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -p $PORT $IP >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: |
          npm ci

      - name: Generate static files
        run: |
          npx hexo g -d

      - name: Rsync to server
        run: |
          rsync -rvz -e "ssh -p $PORT" public/* root@$IP:/home/wwwroot/blog/
