name: Hexo

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

env:
  IP: ${{ secrets.SERVER_IP }}
  PORT: ${{ secrets.SERVER_PORT }}
  KEY: ${{ secrets.SERVER_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -p $PORT $IP >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: |
          npm ci

      - name: Generate static files
        run: |
          npx hexo g -d

      - name: Rsync to server
        run: |
          rsync -rvz -e "ssh -p $PORT" --delete public/ root@$IP:/home/wwwroot/blog/
